### PR TITLE
Update to the newest angular cli version

### PR DESCRIPTION
**Pull request by seopei**
I updated the project to newest angular cli version and removed the "environment switcher" because I think we should go with the angular cli environments.

If you want to switch between environments see the angular cli documentation: https://github.com/angular/angular-cli/wiki/stories-application-environments
Example: you want to build in prod mode but use the local environment: `ng build --prod --env=local`

What do you thing @maximegris?

### CODE REVIEW

**Comment by seopei** [comment]
I also added a watch mode for the electron main file. Now you are able the serve the electron app and if you change the main.ts file the electron will perform a reload.

**Comment by maximegris** [comment]
I actually got 2 issues:

1: in `main.ts`- line 29 : On Windows, this doesn't work. I have to replace it by electron.cmd or by the old value I used `electron: require(`${__dirname}/node_modules/electron`)`. Does this work on your OS (Linux? Mac?) ?

2: in `package.json` : Still on Windows, if I follow the README ${ENV:-local} doesn't work. 
I have to use %ENV% and I can't use conditional variables. :/

**Comment by seopei** [comment]
> 1: in main.ts- line 29 : On Windows, this doesn't work. I have to replace it by electron.cmd or by the old value I used electron: require(${__dirname}/node_modules/electron). Does this work on your OS (Linux? Mac?) ?

I just followed the electron-reload (https://github.com/yan-foto/electron-reload) guide to set this up:
> You could also use the (relatively) new electron package, but you should specify the path directly (no require!): 
> const path = require('path')
> require('electron-reload')(__dirname, {
>    electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });


> 2: in package.json : Still on Windows, if I follow the README ${ENV:-local} doesn't work.
I have to use %ENV% and I can't use conditional variables. :/

I am using Mac and Linux, for Windows there must be a workaround or you have to use a bash for Windows.
What do you use on Windows (Powershell)?

**Comment by whyboris** [comment]
Angular 6.0.0 has just been released (6 hours ago :trollface: ). Maybe bump to the latest version right away?

**Comment by maximegris** [comment]
Hi,

Thanks! Sorry for the late answer. There were several PRs about Angluar&Electron.
I'll merge the PR https://github.com/maximegris/angular-electron/pull/182 .

**Comment by whyboris** [comment]
No problem. Thank you for keeping your repository up to date. Keep up the excellent work ❤️

**Pull request closed without merging**
