### PR TITLE
Angular src restructured as modular 

### PR DESCRIPTION
**Pull request by arunredhu**
Change Logs:
>> Angular src code restructured as modular as per angular official guidelines. Now it contains core and shared modules as well
>> Separate module created for feature and its routing. For e.g. home.module.ts
>> Package.json: "npm run lint" script added to run the linting through npm scripts.
>> .travis.yml: node version 12 added

### CODE REVIEW

**Comment by arunredhu** [comment]
Any update on this??

**Comment by maximegris** [comment]
Hi

Thanks for the PR !

Before merging it, can you please remove your VS Code settings file.

Regards

**Comment by arunredhu** [comment]
Hi,

Removed as you suggested. 

Thanks.

**Comment by maximegris** [comment]
Thanks

Unfortunatly when I packaged the app (.exe) it didn't find the `background.jpg` file.

I think the issue is from `home.component.scss`
`  background: url(/assets/background.jpg) no-repeat center fixed;`
should be replace by this to make it works :
`  background: url(../../assets/background.jpg) no-repeat center fixed;`

To merge the PR, the app sould works with those npm scripts : 
- `npm start`
- `npm ng:serve:web`
- `npm electron:windows / electron:mac / electron:linux`

**Comment by arunredhu** [comment]
Hi,

You were correct, It was the issue with `background-url` property. Thanks for highlighting. 

Also, I upgraded the other dependencies and it is now working fine. Please check.

Thanks.

**Comment by maximegris** [comment]
Great ! Thank a lot 👍

**Pull request merged**
