### PR TITLE
Set environment improvements

### PR DESCRIPTION
**Pull request by seopei**
Some set environment improvements.
You are now able to import the environment like you would do it in a normal cli project: 
`import { environment } from 'environments';`

What do you think @maximegris?

### CODE REVIEW

**Comment by maximegris** [comment]
Well I think that something you want to build your project in "prod" mode (aot, ...), or even "dev" mode but you still want to use different environment variables (local, test, ...). So you can check that your project works on every platform. 
That's why I decolerate environement variables of "cli" variables.

An other approch would be to make XX npm script to cover all possible cases.

**Comment by maximegris** [comment]
Your PR seems OK with this approch. I'll try to find time to test it . Btw thanks a lot :)

**Comment by maximegris** [comment]
I would only change  this : 

To be sure to use `environment.ts` generate on build time.
In `angular-cli.json`
```json
      "environmentSource": "app/environment.ts",
      "environments": {
        "dev": "app/environment.ts",
        "prod": "app/environment.ts"
      }
```

I think it is `export const environment = Object.assign({}, require('../environments/environment.{{ENV}}'));` to fond the correct env file. (in `hooks/environment/environment.ts.tpl`)

**Comment by seopei** [comment]
I made a new PR #169 where I updated the project to the newest cli version and removed the "environment switcher" completely because I thing we should go with the angular cli environments.

Example: you want to build in prod mode but use the local environment: ng build --prod --env=local

**Comment by maximegris** [comment]
Well so you need to add one npm scripts for each environment in order to build in nonprod/prod mode.

Because if you want to launch : 
- in dev mode (npm start) you have to combine `ng serve`- (-env=dev possible?) with `electron:serve`
- generate an electron exe in "dev", you have to combine `ng build --prod --env=dev` with `npm run electron:tsc`

**Comment by seopei** [comment]
Yeah thats true, but you can write something like this in you package.json:

`"ng:serve": "ng serve -o --env=${ENV:-local}",`

If your `ENV` variable is not set it will serve the app with the local environment.

And this will now serve your app with the prod environment:
```
export ENV=prod
npm start
```

And this will now serve your app with the dev environment:
```
export ENV=dev
npm start
```

**Comment by maximegris** [comment]
Ok I see. Can you edit the README in that way ? I will pull your PR then to check all works before merging it :)

**Comment by seopei** [comment]
Yes I can do that.
But I would suggest to decline and not merge this PR because I updated the project to the newest ng cli version and added hot reload to the electron main.ts file (PR #169).

**Comment by maximegris** [comment]
Ok. Thanks. I close this PR :)

**Pull request closed without merging**
