### PR TITLE
Fix #55 , and also added functionality for scripts global building

### LINKED ISSUE #55: Importing css from node modules
I am trying to import bootstrap css file from npm module.

In angular-cli.json:

```
 "styles": [
        "styles.scss",
        "../node_modules/admin-lte/bootstrap/css/bootstrap.css"
]
```

In webpack.config

```
 "styles": [
      "./src/styles.scss",
      "./node_modules/admin-lte/bootstrap/css/bootstrap.min.css"
]
```
Styles are in the style.bundle but don't applied on the DOM

Can someone help me?

Regards

### PR DESCRIPTION
**Pull request by theo4u**
Fix #55 , and also added functionality for scripts since the one from .angular-cli.json is not really functional. 

Now `webpack.config.js` can now be used to handle global `styles` and `scripts`

So you can update the README to help others not pass through same stress

### CODE REVIEW

**Comment by maximegris** [comment]
Thanks 4 the PR !
Can you remove bootstrap.css from the project before merging the PR ?

**Comment by theo4u** [comment]
Done with the removal

**Comment by mo2menelzeiny** [comment]
@linktohack They don't work, you have to include them into the webpack `styles` and `scripts` constants.

**Comment by linktohack** [comment]
Thanks for the confirmation, @mo2menelzeiny, that's what I have found, too.

**Pull request merged**
