### PR TITLE
Update to NodeJS 8, Angular 6, electron 2.0.2, RxJS 6.1 

### PR DESCRIPTION
**Pull request by leo6104**
## Changes
* [x]  Upgrade to angular 6.0.2 (using `ng update @angular/cli` command two times)
* [x]  Remove 'rxjs' blocklist from `tslint.json`, import all members from 'rxjs' 
* [x]  Upgrade to Electron 2.0.2 with bigger favicon (512x512) 
* [x]  Change README.md 
* [x]  Travis CI runs with NodeJS 8 system. (Angular cli 6 supports only 8.9 >=)
* [x]  add lint, e2e, test process to Travis CI
* [x]  remove `hooks`, use `fileReplacements` logic in `angular.json` 
* [x]  Cleanup npm `scripts` with `--` parameter patterns.

## Tests
* [x]  `npm run ng:serve` works! 
* [x]  `npm run build` works!
* [x]  `npm run test` works! 
* [x]  Test with windows 
* [x]  Test with mac

Since Angular 6 supports webpack 4 without node-js built-ins (https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814), `ng serve` shows some warning messages.
```
WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'crypto' in '/Users/sangmin/Desktop/Github/angular-electron/node_modules/zone.js/dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'fs' in '/Users/sangmin/Desktop/Github/angular-electron/node_modules/zone.js/dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'timers' in '/Users/sangmin/Desktop/Github/angular-electron/node_modules/zone.js/dist'
``` 
But, with electron serving, it works well :)

### CODE REVIEW

**Comment by leifwells** [comment]
I am not a PR approver on this project, just a user. I wanted to give this PR a spin since it puts Angular 6 + Electron 2 together. **Everything appears to be working with this PR**, except that when I ran `npm test` I got the following error:
```
angular-electron leifwells$ ng test
 10% building modules 1/1 modules 0 active(node:61074) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
18 05 2018 19:47:07.226:INFO [karma]: Karma v2.0.2 server started at http://0.0.0.0:9876/
18 05 2018 19:47:07.228:INFO [launcher]: Launching browser Chrome with unlimited concurrency
18 05 2018 19:47:07.232:INFO [launcher]: Starting browser Chrome
18 05 2018 19:47:14.227:INFO [Chrome 66.0.3359 (Mac OS X 10.13.4)]: Connected on socket bMIwFgwifkky8WvNAAAA with id 62972712
Chrome 66.0.3359 (Mac OS X 10.13.4): Executed 0 of 0 SUCCESS (0 secs / 0 Chrome 66.0.3359 (Mac OS X 10.13.4): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
```
Not a lot information or clues to debug on from this error and I expect there is something out of date or missing on my computer, but wanted to mention it here.

**Comment by leo6104** [comment]
@leifwells Nice catch :) I found the root cause is the warning messages i mentioned in above. 
The warning messages came from `import 'zone.js/dist/zone-mix';` in `polyfills.ts`.
So, i modify `angular.json` to use polyfills-test.ts instead of polyfills.ts when karma test run.

Also, i add `npm run lint/test/e2e` process in Travis CI. 
Please check @maximegris :)

**Comment by leifwells** [comment]
I can confirm that these updates have resolved my issue mentioned above.

**Comment by maximegris** [comment]
Hi,

Great works ! 
Can you please fix the conflict, I'll merge the PR as soon as possible ;)

**Comment by leo6104** [comment]
@maximegris Thanks :) I fix the conflicts!

**Comment by maximegris** [comment]
Done !

**Pull request merged**
